### ISSUE TITLE
Supported Languages - FAQ vs. AWS Docs

### ISSUE THREAD

**Issue by sringopi** [awsdocs/aws-cloud9-user-guide#14]
AWS FAQ [https://aws.amazon.com/cloud9/faqs/](https://aws.amazon.com/cloud9/faqs/) states over 40 languages are supported.  However, AWS Docs lists only about 15 [languages.](https://docs.aws.amazon.com/cloud9/latest/user-guide/language-support.html)  Where can I find the list of all supported languages?

**Comment by pccornel** [comment]
As of the time of this writing, language support is limited to syntax highlighting for languages not listed in the table in the topic that you reference. Per footnote #1 in that topic: "The AWS Cloud9 IDE provides syntax highlighting for many more languages. For a complete list, in the menu bar of the IDE, choose View, Syntax."
