### ISSUE TITLE
Receiving an error during 'create-role' step

### ISSUE THREAD

**Issue by dhartjes** [awsdocs/aws-cloud9-user-guide#25]
Hello! I have been working on the Create an environment - AWS Cloud9 tutorial which led me to this article, https://docs.aws.amazon.com/cloud9/latest/user-guide/ec2-ssm.html#aws-cli-instance-profiles. Under the heading "Managing instance profiles for Systems Manager with the AWS CLI," there is a script that can be run that looks like:

`aws iam create-role --role-name AWSCloud9SSMAccessRole --path /service-role/ --assume-role-policy-document '{"Version": "2012-10-17","Statement": [{"Effect": "Allow","Principal": {"Service": ["ec2.amazonaws.com","cloud9.amazonaws.com"]      },"Action": "sts:AssumeRole"}]}'

aws iam attach-role-policy --role-name AWSCloud9SSMAccessRole --policy-arn arn:aws:iam::aws:policy/AWSCloud9SSMInstanceProfile

aws iam create-instance-profile --instance-profile-name AWSCloud9SSMInstanceProfile --path /cloud9/

aws iam add-role-to-instance-profile --instance-profile-name AWSCloud9SSMInstanceProfile --role-name AWSCloud9SSMAccessRole`

In my Windows Powershell instance, the first command in this list through the following error (both when copying and pasting, and when typing it in myself):

![image](https://user-images.githubusercontent.com/7397917/100058365-c1b0fc00-2dee-11eb-978c-9a579316073b.png)

Can you please review the script to determine if there is an error? Otherwise, perhaps you can add some additional steps that can be taken to work around this issue.

Thank you very much!
Dominic

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
