### ISSUE TITLE
Lambda Run unavailable when using sam globals

### ISSUE THREAD

**Issue by KyleMit** [awsdocs/aws-cloud9-user-guide#26]
This might be something to forward along to the product team, but probably worth documenting around in the short term.

[SAM Globals](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-template-anatomy-globals.html) allow you to generalize resource properties and apply across all like resources within a file.  It often makes sense to pull the function runtime into the globals section.  However, when you do, the Cloud 9 Lambda Local Run command is greyed out.

### Lambda Run Disabled with Globals:

![lambda run with globals](https://user-images.githubusercontent.com/4307307/100562794-af214180-328a-11eb-88a6-ee4dc7d2e3ed.png)

### Lambda Run Enabled with Inline Definition:

![lambda run without globals](https://user-images.githubusercontent.com/4307307/100562886-f7d8fa80-328a-11eb-81ce-7a3ba13dd26e.png)

Specifically, this page could use the workaround info:

* [Step 4: Run or Debug the Function Locally](https://docs.aws.amazon.com/cloud9/latest/user-guide/tutorial-lambda-run-or-debug-local-function.html)

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
