### ISSUE TITLE
Error when deleting a file that has breakpoints

### ISSUE THREAD

**Issue by bndouglas** [awsdocs/aws-cloud9-user-guide#28]
If you delete a file without first removing breakpoints, the breakpoints persist and aren't deleted. 

Cloud 9 then throws FileNotFound error on ANY file you try to debug, because it is referencing breakpoints in files that no longer exist.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
