### ISSUE TITLE
aws-cloud9-user-guide/doc_source/move-environment.md

### ISSUE THREAD

**Issue by ghost** [awsdocs/aws-cloud9-user-guide#29]
This documentation is out of date. On my vanilla Cloud9 instance both conditions in the shell script are true, triggering the first section, however, the second section (nvme) is what should be run.

https://docs.aws.amazon.com/cloud9/latest/user-guide/move-environment.html#move-environment-resize

```
# evaluates to true, so a new condition needs to be written
if [ $(readlink -f /dev/xvda) = "/dev/xvda" ]
```

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
