### ISSUE TITLE
terminal not working on apple's new M1 chip. When trying to run a script, it doesn't do anything. 

### ISSUE THREAD

**Issue by dotone-101** [awsdocs/aws-cloud9-user-guide#30]
I have purchased a new apple macbook pro M1. I have been using the cloud9 environment fine with my old imac and windows machine. 

The cloud9 environment itself did not have any issues in opening and editing yet. However, when i ran my script, it just kept running (without showing the loading animation) for a weirdly long time. Then i tried running a simple hello world script, but it showed the same symptoms. I tried to open a terminal but it just kept loading. I have python3.8.2 installed on macbook m1 and it's working fine. 
<img width="662" alt="Screenshot 2021-01-18 at 5 08 01 PM" src="https://user-images.githubusercontent.com/77618800/104911232-8b3bcb80-59b0-11eb-84c0-bde1e2d51208.png">
<img width="225" alt="Screenshot 2021-01-18 at 5 09 04 PM" src="https://user-images.githubusercontent.com/77618800/104911235-8d058f00-59b0-11eb-9f9f-4248829d326a.png">

**Comment by dotone-101** [comment]
@Paul-B-AWS kindly help as this issue leaves my cloud9 environment unusable.

**Comment by dotone-101** [comment]
just found out that it's probably an issue with brave browser. It's working in safari.

**Comment by AWS-Shane** [comment]
Thanks for addressing this item.
