### ISSUE TITLE
Is Cloud9 still maintained?

### ISSUE THREAD

**Issue by itsalongstory** [awsdocs/aws-cloud9-user-guide#35]
![image](https://user-images.githubusercontent.com/1243202/178922203-5da82fd0-2101-4b14-a49e-d3a4abcf21a1.png)

Python 2.7 support ended on January 1, 2020, but when I try install C9 on RHEL9, C9 still required Python 2.7.

Most linux distributions have stopped supporting Python 2.

It's hard to imagine that this is the quality of product development at AWS.

**Comment by HernandoR** [comment]
also node.js 12 is end of life

**Comment by HernandoR** [comment]
I'm checking the env of the auto-created EC2 instance. I think that the C9 has moved on the compatibility without updating the install script
![version inside EC2](https://user-images.githubusercontent.com/45709656/210687746-114306b2-6a52-4128-bea0-86ce53bf8206.png)

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
