### ISSUE TITLE
Is that possible go into fullscreen using chrome on android tablet

### ISSUE THREAD

**Issue by zhuyuan2016** [awsdocs/aws-cloud9-user-guide#40]
I like cloud9 so much, so convenient for developers. For now, I built an environment on my AWS EC2 and visit it via my android tablet. However, there are no methods to make cloud9 IDE fullscreen, so always a navigator bar on top of the screen. Please add a `full-scrren` button to function on the IDE layout if possible. Thank you in advance!

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
