### ISSUE TITLE
Description on updating AMi is missing

### ISSUE THREAD

**Issue by elsenhuc** [awsdocs/aws-cloud9-user-guide#7]
Hi,

the page indicates to describe how an AMI of a Cloud9 instance can be updated to the latest version, but I am not able to find the "actual steps" required.

**Comment by pccornel** [comment]
@elsenhuc Are you referring to the "Moving or Resizing an Environment in AWS Cloud9" topic? If so, you can find the actual steps in the "Resizing an Amazon EBS-backed Instance" procedure, which can be found in the _Amazon EC2 User Guide for Linux Instances_ on the AWS Documentation website. 

Note that the contents of the topics in this repo are unconverted reStructuredText. As such, you won't be able to click on most of the links and expect to get to their targets. To see the converted content, preface any of the topics' filenames (for example `move-environment.rst`) with `https://docs.aws.amazon.com/cloud9/latest/user-guide/`, and then change `.rst` to `.html`.
